import { NextRequest, NextResponse } from "next/server"
import { pool } from "@/lib/db"
import { getSessionLeague } from "@/lib/session"

/**
 * Persist a user/assistant exchange after streaming. The thread_id is the UUID
 * generated by the backend's /chat/stream; we create the chat_threads row on
 * first save (scoped to this user + league) and append both messages.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const ctx = await getSessionLeague()
  if (!ctx) return NextResponse.json({ error: "Not authenticated." }, { status: 401 })

  const { id: threadId } = await params
  const { user_message, assistant_message } = await req.json()

  const client = await pool.connect()
  try {
    await client.query("BEGIN")

    // Create the thread if it doesn't exist yet, owned by this user + league.
    await client.query(
      `INSERT INTO chat_threads (id, user_id, league_id)
       VALUES ($1, $2, $3)
       ON CONFLICT (id) DO NOTHING`,
      [threadId, ctx.userId, ctx.leagueUuid]
    )

    // Guard: only the owner can append to their thread.
    const owner = await client.query(
      `SELECT 1 FROM chat_threads WHERE id = $1 AND user_id = $2`,
      [threadId, ctx.userId]
    )
    if (owner.rows.length === 0) {
      await client.query("ROLLBACK")
      return NextResponse.json({ error: "Forbidden." }, { status: 403 })
    }

    // clock_timestamp() (not now()) so the two rows get distinct timestamps
    // within the transaction, keeping user-before-assistant ordering stable.
    await client.query(
      `INSERT INTO chat_messages (thread_id, role, content, created_at)
       VALUES ($1, 'user', $2, clock_timestamp()),
              ($1, 'assistant', $3, clock_timestamp())`,
      [threadId, user_message, assistant_message]
    )

    await client.query(
      `UPDATE chat_threads SET updated_at = now() WHERE id = $1`,
      [threadId]
    )

    await client.query("COMMIT")
    return NextResponse.json({ ok: true })
  } catch (e) {
    await client.query("ROLLBACK")
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Failed to save." },
      { status: 500 }
    )
  } finally {
    client.release()
  }
}
